version: '3.8'

services:
  web:
    build: .
    container_name: kp_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - TZ=Asia/Jakarta
    depends_on:
      - db

  db:
    image: mysql:5.6
    container_name: kp_db
    environment:
      MYSQL_ROOT_PASSWORD: password  
      MYSQL_DATABASE: kp           
    ports:
      - "3306:3306" # Tambahkan baris ini untuk expose port
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
